# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computational Epidemiology
description:
  "PhD Student at UC Berkeley & Researcher at Malaria Modeling Consortium"
repository: https://github.com/slwu89/slwu89.github.io
baseurl:   # the subpath of your site, e.g. /blog
url: https://slwu89.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Sean Wu (吳瑞華)
email: slwood89@gmail.com

navigation:
  - text: Home
    url: /index.html
  - text: Projects
    url: /main/pages/projects.html
  - text: What is Mathematical Epidemiology?
    url: /main/pages/mathEpiSlides.html

projects:
  - name: DHM-Basic
    description: A R Shiny app to calculate basic vector bionomics from an individual based model (Distributed Hazards Model) that can be mapped onto the classic vector parameters of the deterministic Ross-MacDonald framework for models of mosquito-borne infection. This is part of the larger <a href="http://smitdave.github.io/MASH-Development/index.html">MASH</a> project.
    link: https://slwu89.shinyapps.io/DHM-Basic/
    image: https://slwu89.github.io/main/images/MASH_logo.png
  - name: Models of Mosquito-borne Infection
    description: A R Shiny app to demonstrate graphically and interactively the most important mathematical concepts from the 2004 papers <i>"Statics and dynamics of malaria infection in Anopheles mosquitoes"</i> and <i>"The risk of a mosquito-borne infection in a heterogeneous environment"</i>. This is part of the larger <a href="http://smitdave.github.io/MASH-Development/index.html">MASH</a> project.
    link: https://slwu89.shinyapps.io/StaticsDynamics/
    image: https://slwu89.github.io/main/images/MASH_logo.png
  - name: Vector Control Optimization Model (VCOM)
    description: A differential equation based model to investigate effect sizes of modern vector control techniques on <i>Plasmodium falciparum</i> transmission in sub-Saharan Africa. This model is developed as a collaboration between UCSF, UC Berkeley, and Ifakara Health Institute.
    link: http://chipdelmal.github.io/VCOM/
    image: https://slwu89.github.io/main/images/vcom.png
  - name: Safe Genes
    description: A R Shiny app developed for population genetic models of various remedial gene drive strategies. This project is part of the <a href="http://www.darpa.mil/news-events/2016-09-07">DARPA Safe Genes project</a> and is done in collaboration with my advisor, <a href="http://jmarshall.berkeley.edu">John Marshall, PhD</a>.
    link: https://slwu89.shinyapps.io/reversalDrives/
    image: https://slwu89.github.io/main/images/dna.png
  - name: Bayesian Inference
    description: A R Shiny app to help teach Bayesian methods such as Markov Chain Monte Carlo (MCMC), Dirichlet processes, and other topics.
    link: https://slwu89.shinyapps.io/BayesianInference/
    image: https://slwu89.github.io/main/images/bayes.png

presentations:
  - name: What is Mathematical Epidemiology?
    description: A talk I gave on Mathematical Epidemiology in Fall 2016 to my first year PhD seminar at UC Berkeley.
    link: /main/pages/mathEpiSlides.html
    # image: https://slwu89.github.io/main/images/MASH_logo.png

social:
  - service: github
    username: slwu89
    link: https://github.com/slwu89
  - service: twitter
    username: slwu89
    link: https://twitter.com/slwu89
  - service: researchgate
    username: Sean_Wu16
    link: https://www.researchgate.net/profile/Sean_Wu16

# Plugins
gems:
  - jekyll-seo-tag
