# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computational Epidemiology
description:
  "PhD Student at UC Berkeley & Graduate Student Researcher at UC San Francisco"
repository: https://github.com/slwu89/slwu89.github.io
baseurl:   # the subpath of your site, e.g. /blog
url: https://slwu89.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Sean Wu (吳瑞華)
email: slwood89@gmail.com

navigation:
  - text: Home
    url: /index.html
  - text: Projects
    url: /main/pages/projects.html
  - text: Dynamic Programming
    url: http://slwu89.shinyapps.io/dynProgPatch/
  - text: Dynamics of Vector-borne Diseases
    url: https://slwu89.shinyapps.io/StaticsDynamics/
  - text: What is Mathematical Epidemiology?
    url: /main/pages/mathEpiSlides.html

projects:
  - name: DHM-Basic
    description: A R Shiny app to calculate basic mosquit vector bionomics from an individual based model (Distributed Hazards Model) that can be mapped onto the classic vector parameters of the deterministic Ross-MacDonald framework for models of mosquito-borne infection. This is part of the larger MASH project.
    link: https://slwu89.shinyapps.io/DHM-Basic/
    # image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: Models of Mosquito-borne Infection
    description: A R Shiny app to demonstrate graphically and interactively the most important mathematical concepts from the 2004 papers <i>"Statics and dynamics of malaria infection in Anopheles mosquitoes"</i> and <i>"The risk of a mosquito-borne infection in a heterogeneous environment"</i>. This is part of the larger MASH project.
    link: https://slwu89.shinyapps.io/StaticsDynamics/
    # image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: Bayesian Inference
    description: Automatically creates slugs for your Ecto models.
    link: https://slwu89.shinyapps.io/BayesianInference/

social:
  - service: github
    username: slwu89
    link: https://github.com/slwu89
  - service: twitter
    username: slwu89
    link: https://twitter.com/slwu89

# Plugins
gems:
  - jekyll-seo-tag
